# Generated by Django 5.1 on 2024-08-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="order_id",
            field=models.CharField(default="uuid12345", max_length=255),
        ),
    ]
